### ISSUE TITLE
Updating lacrosseview sensor took longer than the scheduled update interval 0:00:30

### ISSUE THREAD

**Issue by nijel** [regulad/hass-lacrosseview#1]
First, thanks for this integration, I wanted to look into writing this myself, but you were faster :-).

Now back to my issue: The hass log is filled with:

```
Updating lacrosseview sensor took longer than the scheduled update interval 0:00:30
```

The problem is that fetching whole history of sensor data takes incredibly long. This can be improved by fetching only the last few entries (the integration anyway only uses the last measurement anyway). So passing `from` while fetching the data heavily improves the performance.

**Comment by nijel** [comment]
https://github.com/regulad/hass-lacrosseview/pull/3 hides the warning by reducing the scan interval, but still, it would be better to fetch less data from the server.

**Comment by regulad** [comment]
I've merged your pull requests. I'm not familiar with an API in home assistant to get the last time an entity was queried, if you could produce documentation of such or a similar API I would gladly make the modification as it would be rather small. 

The code for that is found here, in `regulad/pylacrosseview` (the sister project and library): https://github.com/regulad/pylacrosseview/blob/9a5202bfd7857818627caea3a4519197adc760ec/pylacrosseview/weather_station.py#L134

This library was assembled from existing snippets of code and sniffing traffic from the Android app, so I'm not even sure if it works as I never initially tested that argument.

**Comment by regulad** [comment]
I'm not too concerned with performance as I plan to *eventually* rewrite the parent library with `aiohttp` instead of `requests`.
