### ISSUE TITLE
Can't connect with La Crosse View recently after 2023.5

### ISSUE THREAD

**Issue by PachangaDad** [regulad/hass-lacrosseview#13]
Home assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.03 - Latest

Proxmox VM to itself

All fine until recent 23.5 Update

Hoping this helps to identify issue or provide me with guidance.
Thank you for you development of this integration 

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/lacrosseview/__init__.py:90
Integration: La Crosse View (documentation, issues)
First occurred: 9:55:11 AM (1 occurrences)
Last logged: 9:55:11 AM

Error setting up entry Emailid****@*******.com for lacrosseview
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/lacrosseview/__init__.py", line 90, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by nocturne1** [comment]
Running into this as well.

**Comment by nocturne1** [comment]
Btw, it looks like support for La Crosse View is now built-in to Home Assistant: https://www.home-assistant.io/integrations/lacrosse_view/

Thanks @regulad for your work until native was available!

**Comment by PachangaDad** [comment]
Thanks for the updated redirection to direct integration. All sensors available.
Thank you
