### ISSUE TITLE
Config flow could not be loaded: undefined

### ISSUE THREAD

**Issue by tekwreck** [regulad/hass-lacrosseview#8]
Received an error - Config flow could not be loaded: undefined when trying to install this on my Home Assistant OS.

![image](https://user-images.githubusercontent.com/5428764/170888826-36ae5a15-cc64-4ca6-8d7c-082810478753.png)

**Comment by regulad** [comment]
A little hard to reproduce without any steps. I don't have a HAOS instance available for testing at the moment, but I'm sure I can get it to show up on my instance if you share how you got to here.

Can you please attach your logs?

**Comment by tekwreck** [comment]
So I tried to add the git repo directly as a custom repo which threw an error

![image](https://user-images.githubusercontent.com/5428764/170889282-407827cb-ff30-44a4-b059-5e803daf963a.png)

I used - https://github.com/regulad/hass-lacrosseview

So instead I copied the lacrosseview folder into custom components directly, restarted HA and the LaCrosse View integration was available for installation, however, attempt to install it I got the error above. 

This is only reference I could find in the logs for this integration - 
`homeassistant.requirements.RequirementsNotFound: Requirements for lacrosseview not found: ['pylacrosseview==0.1.5'].
`

**Comment by regulad** [comment]
There appears to be an issue with the manifest. Uninstall the custom repository & integration and try adding it through the official list of HACS repositories.

**Comment by tekwreck** [comment]
So I can't find La Crosse when I search under the official integrations.

![image](https://user-images.githubusercontent.com/5428764/170889630-e697531a-00a6-4cbf-9fb4-301b1c307459.png)

If I go to add the custom repo URL, I get `Invalid Add-on repository!`

![image](https://user-images.githubusercontent.com/5428764/170889619-7271ede6-f42f-4ba9-b64e-c41a30c4cd6b.png)

**Comment by tekwreck** [comment]
Just confirm here's my versions

Home Assistant Core -  2022.3.8 
Home Assistant Operating System - 7.6

**Comment by tekwreck** [comment]
Feel free to close this ticket out, turns out HACS needed to be reinstalled.
